# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 09:08
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171025_1100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='brand_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Brands'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(upload_to=blog.models.upload_to_blog, validators=[blog.models.validate_size]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=blog.models.upload_to_blog_gal),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='post_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=blog.models.upload_to_blog, validators=[blog.models.validate_size]),
        ),
    ]
