# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategory_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='css_class',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='href',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='href',
            field=models.URLField(blank=True, null=True),
        ),
    ]
