# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 13:12
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171026_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(null=True, upload_to=blog.models.upload_to_blog, validators=[blog.models.validate_size]),
        ),
    ]
