# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 09:04
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=models.ImageField(help_text='1360px*440px', null=True, upload_to=blog.models.upload_to_blog_cat, validators=[blog.models.validate_size]),
        ),
    ]
