# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogcategory_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='post_related',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Post'),
        ),
    ]
