# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171106_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['featured', 'date_added']},
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
