# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name_plural': '4. Δημιουργία μηνυμάτων στο κάτω Banner',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=160, verbose_name='Διεύθυνση')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=160, null=True)),
                ('href', models.URLField(blank=True, null=True, verbose_name='Υπερσύνδεσμος')),
            ],
            options={
                'verbose_name_plural': '5. Πληροφορίες Καταστημάτος Αρχικής Σελίδας',
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Use <span> to give color', max_length=60)),
                ('keywords', models.CharField(blank=True, max_length=160, null=True)),
                ('description', models.CharField(blank=True, max_length=160, null=True)),
                ('section_store_header', models.CharField(blank=True, default='ΤΑ ΚΑΤΑΣΤΗΜΑΤΑ ΜΑΣ', max_length=60, verbose_name='Τίτλος Περιοχής Καταστημάτα')),
                ('section_product_header', models.CharField(blank=True, default='ΤΑ ΠΡΟΊΟΝΤΑ ΜΑΣ', max_length=60, verbose_name='Τίτλος Περιοχής Προϊόντα')),
                ('section_product_text', models.TextField(blank=True, default='Insert some text here', verbose_name='Περιγραφή Περιοχής Προϊόντα')),
                ('section_category_header', models.CharField(blank=True, default='ΟΙ ΚΑΤΗΓΟΡΙΕΣ ΜΑΣ', max_length=60, verbose_name='Τίτλος Περιοχής Κατηγορία')),
                ('section_category_text', models.TextField(blank=True, default='Insert some text here', verbose_name='Περιγραφή Περιοχής Κατηγορία')),
                ('section_contact_header', models.CharField(blank=True, default='Μάθετε για εμάς', max_length=60, verbose_name='Τίτλος Περιοχής Contact')),
                ('section_contact_text', models.TextField(blank=True, default='Insert some text here', verbose_name='Περιγραφή Περιοχής Contact')),
                ('section_contact_description', models.TextField(blank=True, default='Insert some text here', verbose_name='Περιγραφή Περιοχής Contact')),
                ('second_banner_title', models.CharField(default='Mήνυμα Banner', max_length=100, verbose_name='Τίτλος Δευτερεύοντος Banner')),
                ('second_banner_icon', models.CharField(default='twitter', max_length=100, verbose_name='Icon Δευτερεύοντος Banner')),
            ],
            options={
                'verbose_name_plural': '1. Διαχείριση Αρχικής Σελίδας',
            },
        ),
        migrations.CreateModel(
            name='IconMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=150)),
                ('delay', models.IntegerField(default=300)),
                ('page_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Homepage')),
            ],
            options={
                'verbose_name_plural': '3. Δημιουργία Icon μηνυμάτων',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=60, verbose_name='Τίτλος')),
                ('image', models.ImageField(upload_to=homepage.models.upload_location, verbose_name='Είκονα')),
                ('text', models.TextField(verbose_name='Περιγραφή')),
                ('href', models.URLField(blank=True, null=True, verbose_name='Υπερσύνδεσμος')),
                ('related_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Homepage', verbose_name='Αρχική Σελίδα')),
                ('store_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_stores.Store', verbose_name='Κατάστημα')),
            ],
            options={
                'verbose_name_plural': '2. Δημιουργία μηνυμάτων στο Βασικού Banner',
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Τηλέφωνο')),
                ('contact_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.ContactInfo')),
            ],
            options={
                'verbose_name_plural': '6. Τηλέφωνα',
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='homepage_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Homepage', verbose_name='Αρχική Σελίδα'),
        ),
        migrations.AddField(
            model_name='bannermessages',
            name='homepage_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Homepage', verbose_name='Αρχική Σελίδα'),
        ),
    ]
