# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name_plural': '2. Δημιουργία Banner'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_category_header',
            field=models.CharField(blank=True, default='ΟΙ ΚΑΤΗΓΟΡΙΕΣ ΜΑΣ', help_text='Μη χρησιμοποιείτε τόνους', max_length=60, verbose_name='Τίτλος Περιοχής Κατηγορία'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_contact_header',
            field=models.CharField(blank=True, default='Μάθετε για εμάς', help_text='Μη χρησιμοποιείτε τόνους', max_length=60, verbose_name='Τίτλος Περιοχής Contact'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_product_header',
            field=models.CharField(blank=True, default='ΤΑ ΠΡΟΊΟΝΤΑ ΜΑΣ', help_text='Μη χρησιμοποιείτε τόνους', max_length=60, verbose_name='Τίτλος Περιοχής Προϊόντα'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_store_header',
            field=models.CharField(blank=True, default='ΤΑ ΚΑΤΑΣΤΗΜΑΤΑ ΜΑΣ', help_text='Μη χρησιμοποιείτε τόνους', max_length=60, verbose_name='Τίτλος Περιοχής Καταστημάτα'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(help_text='Τίτλος Site', max_length=60),
        ),
        migrations.AlterField(
            model_name='iconmessages',
            name='delay',
            field=models.IntegerField(default=300, verbose_name='Καθηστέρηση εμφάνισης'),
        ),
        migrations.AlterField(
            model_name='iconmessages',
            name='text',
            field=models.CharField(max_length=150, verbose_name='Κείμενο'),
        ),
    ]
