# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170720_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('icon', models.CharField(help_text='example fa fa-recycle', max_length=100)),
                ('image', models.ImageField(help_text='370px*370px', upload_to=homepage.models.upload_location)),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='second_banner_icon',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='second_banner_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_category_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_category_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_contact_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_contact_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_contact_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_product_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_product_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_store_header',
        ),
        migrations.AddField(
            model_name='homepage',
            name='circle_image',
            field=models.ImageField(blank=True, help_text='1920px * 794px', null=True, upload_to=homepage.models.upload_location),
        ),
        migrations.AddField(
            model_name='circleimages',
            name='index_page_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Homepage'),
        ),
    ]
