# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20171101_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='circle_image',
            field=models.ImageField(blank=True, help_text='1920px * 794px', null=True, upload_to=homepage.models.upload_location, validators=[homepage.models.validate_size]),
        ),
    ]
