# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20171101_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Περιγραφή'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Τίτλος'),
        ),
    ]
