# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=36.803335, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, default=22.851774, max_digits=8)),
            ],
            options={
                'verbose_name_plural': '1. Διαχείριση Καταστημάτων',
            },
        ),
        migrations.CreateModel(
            name='StoreGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('alt', models.CharField(blank=True, max_length=30, null=True)),
                ('main_image', models.BooleanField(default=False)),
                ('store_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_stores.Store')),
            ],
            options={
                'verbose_name_plural': '2. Gallery Καταστημάτων',
            },
        ),
        migrations.CreateModel(
            name='StoreServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('icon', models.CharField(help_text='fa fa-user', max_length=100)),
                ('page_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_stores.Store')),
            ],
            options={
                'verbose_name_plural': '4. Services Καταστημάτων',
            },
        ),
    ]
