# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StoreWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('time_start', models.CharField(max_length=10)),
                ('time_end', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storework',
            name='store_related',
            field=models.ManyToManyField(to='my_stores.Store', verbose_name='Κατάστημα'),
        ),
        migrations.AddField(
            model_name='storephone',
            name='store_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_stores.Store', verbose_name='Κατάστημα'),
        ),
    ]
