# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_stores', '0002_auto_20170710_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storephone',
            options={'verbose_name_plural': '5. Τηλέφωνα Καταστημάτων'},
        ),
        migrations.AlterModelOptions(
            name='storework',
            options={'verbose_name_plural': '6. Ωράριο Καταστημάτων'},
        ),
        migrations.AddField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=36.803335, max_digits=8, verbose_name='Google map latitude'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=22.851774, max_digits=8, verbose_name='Google map longitude'),
        ),
        migrations.AlterField(
            model_name='store',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Κείμενο'),
        ),
    ]
