# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import my_stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_stores', '0003_auto_20170720_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storegallery',
            name='image',
            field=models.ImageField(upload_to=my_stores.models.upload_location, validators=[my_stores.models.validate_size]),
        ),
        migrations.AlterField(
            model_name='storegallery',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
