# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=60)),
                ('href', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Διαχείριση Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to=products.models.category_upload)),
                ('title', models.CharField(max_length=60)),
                ('href', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('text', models.TextField(blank=True, default='<span> Από..</span> 30.00 €', null=True)),
                ('brands_related', models.ManyToManyField(to='products.Brand')),
            ],
            options={
                'verbose_name_plural': '2. Διαχείριση Κατηγορίας',
            },
        ),
        migrations.CreateModel(
            name='CategoryServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('icon', models.CharField(help_text='fa fa-user', max_length=100)),
                ('page_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
            options={
                'verbose_name_plural': '4. Services Κατηγοριών',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('first_page', models.BooleanField(default=False, verbose_name='Εμφάνιση στην Αρχική Σελίδα')),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField(blank=True, null=True)),
                ('image_href', models.URLField(blank=True, null=True)),
                ('my_moda', models.URLField(blank=True, null=True, verbose_name='Link στο Mymoda.gr')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('store_related', models.ManyToManyField(to='my_stores.Store')),
            ],
            options={
                'verbose_name_plural': '1. Διαχείριση Προϊόντων',
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(upload_to=products.models.product_upload_image)),
                ('main_photo', models.BooleanField(default=True)),
                ('product_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name_plural': '4. Gallery Photo Προϊόντων',
            },
        ),
    ]
