# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170705_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['title'], 'verbose_name_plural': '3. Διαχείριση Brand'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name_plural': '2. Διαχείριση Κατηγορίας'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name_plural': '1. Διαχείριση Προϊόντων'},
        ),
    ]
