# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170707_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='first_page',
            field=models.BooleanField(default=True),
        ),
    ]
